### PR TITLE
Fix GenerateNewFilename function to be much sorter and easy to read.

### LINKED ISSUE #25: Fix ImageLink GenerateNewFilename()
GenerateNewFilename in ImageLink.cs looks a bit scuffed, it has a switch block assigning to `result`, and then right below a big chunk of if/elses assigning to `result` as well, then some commented out code. Looks like the switch is missing a case too? Update this to the new preffered switch expression pattern matching C# feature, much shorter and easier to read. 
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression

Example of switch expression being used in GChan here: https://github.com/Issung/GChan/blob/8345b0cdb3812625cefd961f4a17edde67631d6a/GChan/Controllers/MainController.cs#L319
and here 
https://github.com/Issung/GChan/blob/8345b0cdb3812625cefd961f4a17edde67631d6a/GChan/Utils.cs#L239

### PR DESCRIPTION
**Pull request by orkhanag**
I think this is what you meant. If you believe anything is wrong I can fix it further.

### CODE REVIEW

File: GChan/ImageLink.cs [hunk 1]
```diff
@@ -39,47 +39,55 @@ public string GenerateNewFilename(ImageFileNameFormat format)
...
+            //{
+            //    result = UploadedFilename + " - " + Path.GetFileNameWithoutExtension(URL) + extension;
+            //}
 
             //if (result.Length > FILENAME_MAX_LENGTH)
             //{
             //    result = result.Substring(0, FILENAME_MAX_LENGTH - extension.Length) + extension;
             //}
 
             //Program.Log($"Filename generated: {result}. Length: {result.Length}");
```
Comment (Issung) [inline GChan/ImageLink.cs]: Remove all of this commented-out-code, apart from the logging on line 90.
The logging on line 90 is outdated too, we have since switched to NLog, would you like to while you are here update this line to use NLog, as is done in other files (refer to them for examples).

File: GChan/ImageLink.cs [hunk 2]
```diff
@@ -39,47 +39,55 @@ public string GenerateNewFilename(ImageFileNameFormat format)
...
-                    break;
-                case ImageFileNameFormat.IDAndOriginalFilename:
-                default:
-                    result = Path.GetFileNameWithoutExtension(URL) + " - " + UploadedFilename + extension;
-                    break;
-            }
+                ImageFileNameFormat.ID => lastPart,
+                ImageFileNameFormat.OriginalFilename => UploadedFilename + extension,
+                ImageFileNameFormat.IDAndOriginalFilename => $"{Path.GetFileNameWithoutExtension(URL)}-{UploadedFilename}{extension}",
+                _ => $"{UploadedFilename}-{Path.GetFileNameWithoutExtension(URL)}{extension}",
```
Comment (Issung) [inline GChan/ImageLink.cs]: Since I wrote this I've changed my mind on how to handle unknown values, make line 47 match on the last enum value (OriginalFilenameAndId) and then make the fallthrough `_` throw a new ArgumentException saying the given value for `format` is unknown.

File: GChan/ImageLink.cs [hunk 3]
```diff
@@ -39,47 +39,55 @@ public string GenerateNewFilename(ImageFileNameFormat format)
```
Comment (Issung) [inline GChan/ImageLink.cs:45]: The code above here and code below that that splits on the url and stuff to `Path.GetFileNameWithoutExtension(URL)` to get the file id is not graceful and is actually not needed anymore since we store the file id in the `Tim` property. Use that instead.

**Review by Issung — CHANGES_REQUESTED** [review]
A bit of feedback, this code has obviously been neglected when the new changes were made. The new Tim property for example.

**Review by Issung — DISMISSED** [review]

**Comment by Issung** [comment]
This is looking much better now thanks to your help! Do you have any screenshots of tests you have done to show the different formats are working as intended?

**Comment by Issung** [comment]
I need you to make one small change to this PR before we merge it, I will test it myself when that is ready. I have another issue created and someone agreed to work on it. I will get back to you when that is done and this can be updated.

**Comment by orkhanag** [comment]
Sorry for the late response. I couldn't find how to test the application, it will be great if you test it by yourself. Do you have a particular change in your mind? Or should I make any random changes to PR?

**Comment by Issung** [comment]
No worries! Just leave the PR as is untouched for now, I have someone else making a change soon, when they are done I will get you to update your fork with their changes, then make a small change. I'll notify you when that is :)

**Review by Issung — APPROVED** [review]
Much nicer now.
